### PR TITLE
Update form combo box

### PR DESCRIPTION
**Pull request by midnight-studios**
### The situation
- More customization is requested for third party devs
- This relates to the Form Class, function combo_box() located: (inc/_core/ui/forms/_form.class.php)

### The problem:
- HTML 5 properties (such as placeholder property) support was added for form inputs, but not updated for combo_box
- The user is forced to use the current select list label 'New' when something else such as 'Other' would work better. Allowing this to be specified as needed is best
- Currently a custom inline javascript event 'onchange' is not supported
- Currently a custom class can not be assigned to the input field inside combo input

### This pull request provides: 
* Support placeholder property
* Support custom input class
* Support custom label for new option label
* Support custom javascript 'onchange' event

### CODE REVIEW

**Comment by midnight-studios** [comment]
I understand. Please see the initial for the amendments

**Comment by fplanque** [comment]
@midnight-studios Thanks This is better and I do get a general understanding of the problem but again you made me waste 5 minutes in guesswork instead of giving me a screenshot of what b2evo does BEFORE mods and another AFTER mods (or anotated to explain changes).

I will spend the 5 minutes here but certainly won't if I find some more requests that require guesswork in the same streak. I have a list of about 150 items to go though (on 8 different platforms)

**Comment by yurabakhtin** [comment]
@midnight-studios I reviewed your changes and understand them but couldn't agree them to be committed, so I have done what you want in my new commit https://github.com/b2evolution/b2evolution/commit/58a0f77b995e98178256753507562c1649767a1f and you can customise now any param of `<select>` and `<input>` from the `Form->combo_box()`, see default params:

```php
	// Params for <select>(main element):
	'class'                    => 'form-control input-sm', // Style class
	'onchange'                 => '', // Append JavaScript code to event "onchange" with default value "check_combo(this);"
	'new_option_value'         => 'new', // Value of new option
	'new_option_label'         => T_('New').': ', // Label/title of new option
	// Params for <input>(additional element to enter new value/option):
	'new_field_params'         => array(), // Additional attributes except of the defined below (Array: key - attr name, value - attr value)
	'new_field_type'           => 'text', // Field type
	'new_field_id'             => $field_name.'_combo', // Attribute "id"
	'new_field_name'           => $field_name.'_combo', // Attribute "name"
	'new_field_class'          => 'form-control input-sm', // Normal style class
	'new_field_class_error'    => 'field_error', // Style class for error
	'new_field_class_required' => 'field_required', // Style class for required
	'new_field_size'           => 30, // Attribute "size"
	'required'                 => false, // TRUE for required new value
	'placeholder'              => NULL, // Placeholder
```

If it is enough, I think you can close this PR, thanks.

**Comment by midnight-studios** [comment]
Thank you @yurabakhtin

**Pull request closed without merging**
