### PR TITLE
Feature/label after input param

### PR DESCRIPTION
**Pull request by midnight-studios**
@fplanque I am aware you requested not to duplicate requests, so I do apologize, but this request was submitted Oct 04, 2017 on b2evolution forums and seems to have fallen unnoticed. 

The just of this PR is to support custom styled checkboxes (or radio inputs) with styling such as:

`input[type='checkbox'] + label { // rules... } input[type='checkbox']:checked + label { // rules... }`

This is not possible if the label opening tag proceeds the input element.

This is what @mgsolipa came up with.

@see http://forums.b2evolution.net/form-class-form-inputs-format-checkbox

### CODE REVIEW

**Comment by fplanque** [comment]
Please post:

- the smallest possible HTML snippet of what is generated by b2evolution right now 
- the smallest possible HTML snippet of what you would like b2evolution to generate

**Comment by fplanque** [comment]
ok, so I understand what you want to do, I still don't really know why because you never started with a why... which means: a screenshot of what a checkbox currently looks like and another of how you want it to look like (preferably in some context that makes some sense).

Because this is "a lot" of added code which creates additional technical debt and maintenance weight and it should only be added if there is a good reason.

Being able to do `input[type='checkbox']:checked + label { // rules... ` for the sake of being able to do it is not a good reason.

**Comment by midnight-studios** [comment]
@fplanque it is about striking a balance between functionality and aesthetics. This request serves that purpose. More specifically it expands the ability for customization of (aesthetically appealing) themes. It will service the needs of those who like to customize their skin's visual presentation. Doing this will (expand options for customization) (help to) attract more (skin designers) end users.
 
This request makes customization of checkboxes and radio options used in skins ect simpler with less effort. In this case, simply css can drastically change the 'default' look of the aforementioned elements.

Such as applying something like this:
https://lokesh-coder.github.io/pretty-checkbox/

Kindly keep in mind that time is valuable to everyone. I truly hope that this explanation meets your needs.

**Comment by fplanque** [comment]
All I need is a compelling screenshot of a use case.

This Pretty Checkbox library looks good indeed. But as far as I can see it requires an even more elaborate HTML structure than what this PR generates. 

So again, without a compelling screenshot of how the PR can be used in real life, to me this is added code with no practical purpose.

**Comment by midnight-studios** [comment]
There may be some complexity, but I looked at this in some detail and used it and the main thing it needed to work is the ability to apply css rules that rely on the structure input[type='checkbox']:checked + label because what it actually does, is hide the real checkbox and uses the label tag to insert the new item.

If this library can be included in b2e it will solve the problem and this PR will be null and void

**Comment by yurabakhtin** [comment]
@midnight-studios Please see my attached screenshot: 

I think you can do this with modifying your skin:

```php
function get_template( $name )
{
	switch( $name )
	{
		case 'your_custom_checkboxes_form':
			return array_merge( $this->get_template( 'Form' ), array(
					'inputstart_checkbox' => '<div class="controls col-sm-9 your_custom_checkbox_wrapper_class">',
					'inputend_checkbox'   => "</div>\n",
					'note_format'         => '<label for="$ID$">%s</label>',
				) );
	}

	return parent::get_template( $name );
}
```

then you can use this in your forms like:

```php
$Form->switch_layout( 'your_custom_checkboxes' );
$Form->checkbox_input( 'checkbox_name2', 0, '', array( 'note' => T_('Checkbox 2 note') ) );
$Form->checkbox_input( 'checkbox_name3', 0, '', array( 'note' => T_('Checkbox 3 note') ) );
$Form->checkbox_input( 'checkbox_name4', 0, '', array( 'note' => T_('Checkbox 4 note') ) );
$Form->switch_layout( NULL );
```

Currently the `$ID$` is not replaced with proper value in `'<label for="$ID$">` yet but if such solution is enough for you, then we can easy implement the `$ID$` replacing instead of that implementation for param `label_after_input` what @mgsolipa did.

**Comment by fplanque** [comment]
I did not intend to close this, I just renamed the branch to `old/develop`.

**Pull request closed without merging**
