### PR TITLE
Added an option in the collection-title-widget for adding a link in the title or not

### PR DESCRIPTION
**Pull request by doctortoffu**
Hello there,

Currently, the "collection title widget" always adds a link to the collection in the collection title. I reckon that such behaviour doesn't make sense, especially in the homepage, because it just leads back to the same page the browser currently is displaying. But I imagine that such behaviour may be useful in other cases for some people, so I added an option in the widget settings that allows the user to decide whether to place a link in that title or not.

Please accept the change :-)

Cheers.

### CODE REVIEW

**Comment by fplanque** [comment]
Hi, instead of a 2 state option that would later need upgrade code to move to a 3 state option, please make it directly a radio option with 3 options similar to what is used in other places of b2evolution:

Add link:

o Always
o Auto (only when not already on collection front page)
o Never

**Comment by doctortoffu** [comment]
Hi François,

Sorry for the late reply but life has a habit of getting in the way :-)

I made the change you recommended. Though I couldn't find exact documentation about how does b2evolution detects when it's displaying a collection frontpage or the homepage, it seems that it would depend on the value of the $disp variable, is that correct? Assuming that's the case, this code checks whether $disp == 'front' to decide on whether is the frontpage or not.

Hope I made the right call.

Cheers.

**Comment by fplanque** [comment]
Hi, no the front page can be set to almost any disp, so this code is not correct.

**Comment by doctortoffu** [comment]
Hi again,

Bummer. May I ask then how does b2evolution detects the frontpage? Can't find documentation about that.

Cheers.

**Comment by doctortoffu** [comment]
Hi François,

So, I found new information that pointed me in the direction of the $is_front variable. As it's set to true when b2evolution detects that is displaying the frontpage, I've adjusted the code accordingly.
Just tested it against several types of disp in the URL and worked perfectly well.
Please let me know if now it's OK.

Cheers.

**Comment by fplanque** [comment]
ok, so this makes sense but your pull request is for master and we want to merge this into the `develop` branch. 
Can I change this pull request? Can you change it? Does this require a separate pull request?

**Comment by doctortoffu** [comment]
Sorry for the late reply. I'll check this code against the develop branch and then adjust the pull request ASAP.
Cheers.

**Comment by doctortoffu** [comment]
OK, so I checked the code against the 'develop' branch and it was fine, so I just changed the base branch for this pull request and it shows no conflicts.
Hope everything is fine now.
Cheers.

**Comment by fplanque** [comment]
I did not intend to close this, I just renamed the branch to `old/develop`.

@doctortoffu It seems I cannot change the branch myself, can you change the base branch to `7.2dev` (if it conflicts and you cannot fix conflicts, use `release/6.11.x`) Thanks.

**Comment by doctortoffu** [comment]
I tried to edit the base branch but I couldn't as the pull request is closed, so I'll create a new one with the right branch.
Cheers.

**Pull request closed without merging**
