### PR TITLE
Added option in user settings to show or hide user Reputation data to anonymous visitors...

### PR DESCRIPTION
**Pull request by doctortoffu**
Added an option in user settings to show or hide Reputation data from the user information when it is displayed in the front-office to an anonymous user (not logged in).
Also added an option to allow blurring the user avatar image (current behaviour) or instead display a clear picture (desired behaviour) just like the one is normally displayed to logged in users.
Finally also modified the user display view to hide username, age and sex when displayed to an anonymous user (not logged in) as those are sensitive private information that should not be exposed to everyone. Didn't make that an option because I reckon it should be standard behaviour to protect privacy, but if you want me to I could also make that an option and send another pull request.
I made these changes because I'm developing a site that is not exactly a blog but instead a business site, and it really made no sense to show Reputation, age, sex, or username when introducing visitors to the people that work in the business. Then I reckoned that these settings could be useful for other users as well, and I also wouldn't want to hack the code again for every new b2evolution release :-)
Please accept these changes! Thanks in advance!

### CODE REVIEW

**Comment by fplanque** [comment]
These changes seem to make sense globally but it's too hard to figure out exactly what you did from the description and the code. Please post screenshots of before/after.

**Comment by doctortoffu** [comment]
Hi François,
Sure thing. This a screenshot of how the user page is displayed without my modifications:
previous_behaviour

Please note though that the username, age and sex are hidden because I didn't make that an option. The unmodified code would show that data.

And this other screenshot is for my current page enabling the options:
desired_behaviour

Hope that helps.
Cheers.

**Comment by doctortoffu** [comment]
I just made sure to follow the b2evo code style conventions and changed the base branch to "develop". Checked all the code and there's no conflicts.
Cheers.

**Comment by fplanque** [comment]
I did not intend to close this, I just renamed the branch to `old/develop`.

@doctortoffu It seems I cannot change the branch myself, can you change the base branch to `7.2dev` (if it conflicts and you cannot fix conflicts, use `release/6.11.x`) Thanks.

**Comment by doctortoffu** [comment]
I tried to edit the base branch but I couldn't as the pull request is closed, so I'll create a new one with the right branch.
Cheers.

**Pull request closed without merging**
