### PR TITLE
Added an error message to warn the user that the requested organisation has no members

### PR DESCRIPTION
**Pull request by doctortoffu**
Hi there,
Currently, the "Organization Members" Widget doesn't let the user know when the chosen organization has no members. This is specially inconvenient because there's another bug (which I haven't yet pinpointed) where b2evolution removes a member from the organization where it is a member every time I update any information in the user profile. As the widget just presented a blank space it took me a while to realise that the other bug had removed the only user from the requested organization.
This code address this problem by presenting an error message stating the group has no members.
Hope you find it OK to merge :-)

Cheers.

### CODE REVIEW

**Comment by fplanque** [comment]
- Please post a screenshot of where that error message displays
- Please follow b2evo conventions on position of {

**Comment by doctortoffu** [comment]
Hi François,

Here's a screenshot from the widget displaying the sole member of the chosen organisation:
One_member

And here's a screenshot from the widget displaying that there's no member assigned to the chosen organisation (hence, you can notice exactly why the widget doesn't display the expected profile and then fix it on the backend):
No_members

I'll fix the bracket tomorrow and update the commits. Hope this helps to clarify what I did
Cheers.

**Comment by doctortoffu** [comment]
Hi François,
Fixed the style to follow b2evo conventions and also changed the base branch to develop.
Cheers.

**Comment by fplanque** [comment]
I did not intend to close this, I just renamed the branch to `old/develop`.

@doctortoffu It seems I cannot change the branch myself, can you change the base branch to `7.2dev` (if it conflicts and you cannot fix conflicts, use `release/6.11.x`) Thanks.

**Comment by doctortoffu** [comment]
I tried to edit the base branch but I couldn't as the pull request is closed, so I'll create a new one with the right branch.
Cheers.

**Pull request closed without merging**
