### PR TITLE
Config expandet

### PR DESCRIPTION
**Pull request by Justman10000**
Added the following:

- Toggle whether the footer should be displayed
- Determine the mode of the footer, either default or set custom to be able to declare your own footer more easily
- Toggle whether to show the app footer and copyright text
- Toggle whether the icon should be displayed
- Determine the icon, either the default ixon or your own

<br>

- [x] Tested on own system

### CODE REVIEW

**Comment by Justman10000** [comment]
@fplanque

**Comment by Justman10000** [comment]
@fplanque

**Comment by Justman10000** [comment]
@fplanque

**Comment by Justman10000** [comment]
CANNOT YOU DISSECT ONCE BEFORE CLOSING A PR? Then die with your 0815 shit! Regulate your shit yourself! I have invested my time and effort! Do you care? APPARENTLY NOT! No more support from me!

**Comment by fplanque** [comment]
I am not maintaining b2evolution any more.

**Comment by Justman10000** [comment]
> I am not maintaining b2evolution any more.

And that is now a reason to close PR s? Then fuck off with the project, if it is no longer maintained anyway! And you can leave the comments quietly, so that all know how you deal with your community...

**Comment by Justman10000** [comment]
> I am not maintaining b2evolution any more.

And that is now a reason to close PRs? Then fuck off with the project, if it is no longer maintained anyway! And you can leave the comments quietly, so that all know how you deal with your community...

**Pull request closed without merging**
