### PR TITLE
Feature dynamic select input

### PR DESCRIPTION
**Pull request by midnight-studios**
# Usage

The features these changes provides can be used in different use cases of which will most commonly be utilized by plugins.

## Use case example

An example will be a survey form. The admin may wish to create a form that may require numerous form input fields. 

Some might be as simple as  question and answer consisting of some Question Text and a feedback/answer text input field, however the admin might wish to use more complex feedback options, such as a radio group, checklist or select list. This will require the plugin to support more complex functionality as the admin would be required to add input properties such as  option values and labels.

Each Form Input Item may consist of any of the following types:

- 'select'
- 'integer'
- 'html_input'
- 'html_textarea'
- 'textarea'
- 'text'
- 'checkbox'
- 'checklist'
- 'radio'
- 'fileselect'
- 'password'
- 'info'
- 'color'
- 'input_group'

Each Form Input will be added dynamically in order to build the form as needed, and each input property will also be required to be added dynamically for some inputs such as lists, may need only two or three list items, while others may be more.

This feature therefor provides support for nested dynamic inputs such as types 'select_input' inside array:array:string.

Additional use case examples will include complex settings for a shopping cart plugin, courier/shipping plugin, layer slider plugin  

## Changes

This branch contains support for a feature not available in the Official Branch:

- Fixes for dynamic types: array:array:string (fix removing and re-adding items via AJAX callbacks)
- Support for new dynamic type: select_input https://github.com/b2evolution/b2evolution/pull/63
- Support for nested dynamic types https://github.com/b2evolution/b2evolution/pull/56
- Fixes loading default value for type input_group https://github.com/b2evolution/b2evolution/pull/72
- Fixes for support dynamic type array:array:string in Skin Settings https://github.com/b2evolution/b2evolution/pull/76/commits/7447189e0678b9640fbb1685bddbd715f218d019

# Configurations:

- type			= select_input
- max_number	= 4
- use_fieldset 	= true / false  (Wrap the items in a fieldset)
- fold			= true / false

## Supports:

- 'select'
- 'integer'
- 'html_input'
- 'html_textarea'
- 'textarea'
- 'text'
- 'checkbox'
- 'checklist'
- 'radio'
- 'fileselect'
- 'password'
- 'info'
- 'color'
- 'input_group'

# Related PR

This PR incorporates all the following:

- https://github.com/b2evolution/b2evolution/pull/74
- https://github.com/b2evolution/b2evolution/pull/72 
- https://github.com/b2evolution/b2evolution/pull/63
- https://github.com/b2evolution/b2evolution/pull/56

## Forum Discussions

http://forums.b2evolution.net/support-dynamic-fields-inside-dynamic-fields#c110631
http://forums.b2evolution.net/feature-request-dynamic-input-groups#c110422

### CODE REVIEW

**Comment by fplanque** [comment]
@midnight-studios can you relink the use case description here please?

**Comment by midnight-studios** [comment]
@fplanque I amended the initial comment above with a **usage**  and **use case** section

**Comment by yurabakhtin** [comment]
@fplanque @midnight-studios I have tested new setting type `select_input`, please see my screenshot. As I understand the new `select_input` is a multiple version of existing type `input_group` to allow add several such groups dynamically.

**Comment by midnight-studios** [comment]
@yurabakhtin  the items in your screenshot is fixed in https://github.com/b2evolution/b2evolution/pull/76/commits/8400127ff3abb55b3e83514b0969a8c56cb0127a i also included additional types samples handled by 'select_input' https://github.com/b2evolution/b2evolution/pull/76/commits/862516af6e9b2ed79606ebd9d788542058745489, also note that dynamic calls don't work on Skin Settings as per below bug report and this bug has no relation to (caused by) this pull request 


http://forums.b2evolution.net/bug-6-9-x-dynamic-plugin-settings-not

**Comment by midnight-studios** [comment]
@yurabakhtin I addressed all the issues in your screenshot:

* Fixed max number on form submitting issue https://github.com/b2evolution/b2evolution/commit/8400127ff3abb55b3e83514b0969a8c56cb0127a
* Fixed loading default values in dynamic calls https://github.com/b2evolution/b2evolution/pull/76/commits/bd37c5033e75e9b68256acfc7c4354f56aca33f2
* Fixed type array:array:string for skin settings: https://github.com/b2evolution/b2evolution/pull/76/commits/7447189e0678b9640fbb1685bddbd715f218d019

**Comment by yurabakhtin** [comment]
@midnight-studios I have tested last version of this PR and yes it seems it works without errors, thanks.
So a difference between existent type "Dynamic Type `array:array:string`" and your new added "Select Input `select_input`" is that "Select Input" allows user to select what field or group of field will be added, but the "Dynamic Type" adds only a specific set of the fields which are defined in config of skin/plugin/widget.

**Comment by midnight-studios** [comment]
@yurabakhtin that is 100% accurate. Thanks

**Pull request merged**
