### PR TITLE
Install fixes

### PR DESCRIPTION
**Pull request by keithbowes**
When I tried a fresh install, I encountered some errors.  Here are my fixes for them.

### CODE REVIEW

**Comment by fplanque** [comment]
Why did you change the special characters from hexadecimal notation to non-ASCII chars?

**Comment by keithbowes** [comment]
The hexadecimal notation caused SQL errors.

**Comment by fplanque** [comment]
What DB and version are we using?

We need to keep the source code in ASCII-7 format otherwise we always end up with some contributor killing the special chars.

**Comment by keithbowes** [comment]
I'm using my distro-supplied MariaDB, currently 10.0.31.  I suppose people installing b2evolution will just have to manually edit some SQL statements one way or another.  I suppose this patch should be marked as invalid or whatever.

**Pull request closed without merging**
